[[edge_functions]]
    function = "custom-content"
    path = "/resume"

[[plugins]]
    package = "netlify-plugin-inngest"

    [plugins.inputs]
        host = "https://allons-y.llc"

[[plugins]]
    package = "@netlify/plugin-sitemap"

    [plugins.inputs]
        buildDir = "public"
        exclude = './public/resume/*.html'
