name: Build validation

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - main

jobs:
  build-validation:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v6

      - name: Enable Corepack
        run: corepack enable

      - name: Use Node LTS version
        uses: actions/setup-node@v6
        with:
          cache: yarn
          node-version: 24

      - name: Install dependencies
        run: yarn install --immutable

      - name: Validate build
        run: yarn ci
        env:
          INNGEST_APP_ID: ${{ secrets.INNGEST_APP_ID }}
          NETLIFY_BUILD_HOOK_URL: ${{ secrets.NETLIFY_BUILD_HOOK_URL }}
          MYSQL_HOST: ${{ secrets.MYSQL_HOST }}
          MYSQL_PORT: ${{ secrets.MYSQL_PORT }}
          MYSQL_USER: ${{ secrets.MYSQL_USER }}
          MYSQL_PASS: ${{ secrets.MYSQL_PASS }}
          MYSQL_DB: ${{ secrets.MYSQL_DB }}

      - name: Check for uncommitted changes
        run: git diff --exit-code
